RevenuePlanner/Controllers/OrganizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using RevenuePlanner.Models;
using RevenuePlanner.BDSService;
using Elmah;
using RevenuePlanner.Helpers;
using System.Data;
using System.Transactions;

namespace RevenuePlanner.Controllers
{
    public class OrganizationController : CommonController
    {
        //
        // GET: /Organization/

        #region "Variables"
        private BDSService.BDSServiceClient objBDSServiceClient = new BDSService.BDSServiceClient();
        private MRPEntities db = new MRPEntities();
        #endregion

        #region "Index"
        public ActionResult Index()
        {
            return View();
        }
        #endregion

        #region "Roles related Methods"
        /// <summary>
        /// Manage Role.
        /// </summary>
        /// <returns>Return ManageRoles view with RoleModel.</returns>
        [AuthorizeUser(Enums.ApplicationActivity.UserAdmin)]  // Added by Sohel Pathan on 24/06/2014 for PL ticket #537 to implement user permission Logic
        public ActionResult ManageRoles()
        {
            // Added by Sohel Pathan on 24/06/2014 for PL ticket #537 to implement user permission Logic
            ViewBag.IsIntegrationCredentialCreateEditAuthorized = AuthorizeUserAttribute.IsAuthorized(Enums.ApplicationActivity.IntegrationCredentialCreateEdit);
            ViewBag.IsUserAdminAuthorized = AuthorizeUserAttribute.IsAuthorized(Enums.ApplicationActivity.UserAdmin);

            List<RoleModel> listrolemodel = new List<RoleModel>();
            try
            {
                BDSService.BDSServiceClient bdsuserrepository = new BDSServiceClient();

                //Added By : Kalpesh Sharam bifurcated Role by Client ID - 07-22-2014 
                var memberlist = bdsuserrepository.GetAllRoleList(Sessions.ApplicationId, Sessions.User.ClientId);

                // Added by dharmraj to remove above foreach loop, 10-7-2014
                //// Get Members Role details.
                listrolemodel = memberlist.Select(member => new RoleModel
                                                 {
                                                     RoleTitle = member.Title,
                                                     RoleCode = member.Code,
                                                     RoleId = member.RoleId
                                                 }).ToList();
            }
            catch (Exception e)
            {
                ErrorSignal.FromCurrentContext().Raise(e);

                //To handle unavailability of BDSService
                if (e is System.ServiceModel.EndpointNotFoundException)
                {
                    return RedirectToAction("ServiceUnavailable", "Login");
                }
                else
                {
                    TempData["ErrorMessage"] = Common.objCached.ErrorOccured;
                }
            }

            return View(listrolemodel.AsEnumerable());
        }

        /// <summary>
        /// Add new Role.
        /// </summary>
        /// <param name="roledesc">Role Decription</param>
        /// <returns>Return flag value in Json</returns>
        [HttpPost]
        public JsonResult AddRole(string roledesc)
        {
            if (string.IsNullOrEmpty(roledesc))
                return Json(false);

            //// Add New Role description to Tempdata.
            BDSService.Role objrole = new BDSService.Role();
            objrole.Description = roledesc;////Modified by Mitesh Vaishnav on 07/07/2014 for PL ticket #584
            objrole.Title = roledesc;////Modified by Mitesh Vaishnav on 07/07/2014 for PL ticket #584
            TempData["objrole"] = objrole;

            try
            {
                //Added By : Kalpesh Sharam bifurcated Role by Client ID - 07-22-2014 

                //// Check Role duplication.
                int retval = objBDSServiceClient.DuplicateRoleCheck(objrole, Sessions.ApplicationId, Sessions.User.ClientId);

                //// if duplicate role then return false otherwise true.
                if (retval == 1)
                    return Json(true);
                else
                    return Json(false);
            }
            catch (Exception e)
            {
                ErrorSignal.FromCurrentContext().Raise(e);

                //// Flag to indicate unavailability of web service.
                //// Added By: Maninder Singh Wadhva on 11/24/2014.
                //// Ticket: 942 Exception handeling in Gameplan.
                if (e is System.ServiceModel.EndpointNotFoundException)
                {
                    return Json(new { serviceUnavailable = Url.Content("#") }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(false);
        }

        /// <summary>
        /// Edit Role.
        /// <param name="roleId">Edit Role details by RoleId</param>
        /// </summary>
        /// <returns>Return RoleEdit view</returns>
        [AuthorizeUser(Enums.ApplicationActivity.UserAdmin)]  // Added by Sohel Pathan on 24/06/2014 for PL ticket #537 to implement user permission Logic
        public ActionResult RoleEdit(Guid roleId)//changed by uday for functional review point...3-7-2014;
        {
            // Added by Sohel Pathan on 24/06/2014 for PL ticket #537 to implement user permission Logic
            ViewBag.IsIntegrationCredentialCreateEditAuthorized = AuthorizeUserAttribute.IsAuthorized(Enums.ApplicationActivity.IntegrationCredentialCreateEdit);
            ViewBag.IsUserAdminAuthorized = AuthorizeUserAttribute.IsAuthorized(Enums.ApplicationActivity.UserAdmin);

            try
            {
                BDSService.BDSServiceClient bdsuserrepository = new BDSServiceClient();

                //Added By : Kalpesh Sharam bifurcated Role by Client ID - 07-22-2014 
                var rolelist = bdsuserrepository.GetAllRoleList(Sessions.ApplicationId, Sessions.User.ClientId);
                if (roleId == Guid.Empty)//changed by uday for functional review point...3-7-2014;
                {
                    var prevrole = (Role)TempData["objrole"];//changed by uday for functional review point...3-7-2014;
                    if (prevrole != null)
                    {
                        ViewBag.current = prevrole.Description;
                    }
                    ViewBag.roleid = roleId;
                }
                else
                {
                    ViewBag.current = rolelist.Where(role => role.RoleId == roleId).Select(role => role.Title).FirstOrDefault();
                    ViewBag.roleid = roleId;
                    ViewBag.colorcode = rolelist.Where(role => role.RoleId == roleId).Select(role => role.ColorCode).FirstOrDefault();

                    rolelist = rolelist.Where(role => role.RoleId != roleId).ToList();
                }
                List<RoleModel> listrolemodel = new List<RoleModel>();
                IList<SelectListItem> RoleList = new List<SelectListItem>();
                RoleList = rolelist.Select(role => new SelectListItem() { Text = role.Title, Value = role.RoleId.ToString(), Selected = false })
                                .OrderBy(it => it.Text, new AlphaNumericComparer()).ToList();

                //// Get Application Activity.
                var activitylist = bdsuserrepository.GetUserApplicationactivitylist(Sessions.ApplicationId);

                //// Get Role Activity permissions by RoleId.
                var filterlist = bdsuserrepository.GetRoleactivitypermissions(roleId);
                ViewData["permissionlist"] = filterlist;
                ViewData["activitylist"] = activitylist;

                string ids = string.Empty;
                if (filterlist.Count > 0)
                {
                    ids = string.Join(",", filterlist.Select(filter => filter.ApplicationActivityId.ToString()).ToArray());
                }//commented by uday for functional review point...3-7-2014
                ViewData["permissionids"] = ids.ToString();
                TempData["RoleList"] = new SelectList(RoleList, "Value", "Text");
            }
            catch (Exception e)
            {
                ErrorSignal.FromCurrentContext().Raise(e);

                //To handle unavailability of BDSService
                if (e is System.ServiceModel.EndpointNotFoundException)
                {
                    return RedirectToAction("ServiceUnavailable", "Login");
                }
                else
                {
                    TempData["ErrorMessage"] = Common.objCached.ErrorOccured;
                }
            }

            return View();
        }

        /// <summary>
        /// Delete Role.
        /// <param name="roleid">User RoleId</param>
        /// <param name="selectedrole">Role Text</param>
        /// </summary>
        /// <returns>Return RoleDelete partialview.</returns>
        [AuthorizeUser(Enums.ApplicationActivity.UserAdmin)]  // Added by Sohel Pathan on 24/06/2014 for PL ticket #537 to implement user permission Logic
        public ActionResult RoleDelete(Guid roleid, string selectedrole)
        {
            try
            {
                ViewData["users"] = objBDSServiceClient.GetRoleMemberList(Sessions.ApplicationId, roleid);
                //changed by uday for functional review point...3-7-2014;

                BDSService.BDSServiceClient bdsuserrepository = new BDSServiceClient();

                //Added By : Kalpesh Sharam bifurcated Role by Client ID - 07-22-2014 
                var rolelistData = bdsuserrepository.GetAllRoleList(Sessions.ApplicationId, Sessions.User.ClientId).Where(rolelist => rolelist.RoleId != roleid).ToList().Select(role => new SelectListItem()
                {
                    Text = role.Title,
                    Value = Convert.ToString(role.RoleId),
                }).OrderBy(role => role.Text, new AlphaNumericComparer());

RevenuePlanner/Views/Organization/CheckPermission.cshtml
@using RevenuePlanner.BDSService;
@using RevenuePlanner.Helpers;
@{
    var lstUsers = ViewData["users"] == null ? new List<User>() : (List<User>)ViewData["users"];
    var lstpermissions = ViewData["apptitle"] == null ? new List<string>() : (List<string>)ViewData["apptitle"];
}
@Html.Hidden("SuccMsg", TempData["SuccessMessage"])
<!--success message-->
<div id="successMessage" class="alert hide alert-success message-position">
    <a class="close">×</a>
    <div id="cSuccess"><strong>Success.</strong> @Html.Raw(HttpUtility.HtmlDecode((string)TempData["SuccessMessage"]))</div>
</div>

<!--div to display pop up for Delete role-->
<div id="DivPartialShareTacticCheck"> 
    <div class="all-height DivResetDefaults" id="DivShareTacticPopupMainDel">
        <div class="calc-height">
            <div class="span12">
                <div id="DivDeleteRolePopup" class="form-inspect-share hide fade in height-auto popup" role="dialog" style="display: block;">
                    <div style="padding-bottom: 20px;" class="login-wrapper">
                        <h4 class="source-sans-prolight">You are about to remove the permission:</h4>
                         @if (lstpermissions.Count > 0)//change for validation
                         {
                             <div class="affected-list">
                                    <ul class="source-sans-proregular">
                                        @foreach (var item in lstpermissions)
                                        {
                                            <li>@Html.Raw(item)</li>//name change by uday for functional review point...3-7-2014                              
                                        }
                                    </ul>
                                </div>
                         }
                        @if (lstUsers.Count > 0)//change for validation
                        {
                            <div class="affected-area">
                                <h5 class="source-sans-prosemibold">The users below will be affected:</h5>
                                <div class="affected-list">
                                    <ul class="source-sans-proregular">
                                        @foreach (var item in lstUsers)
                                        {
                                            var displayname = item.LastName + ',' + item.FirstName;
                                            <li>@displayname</li>                           
                                        }
                                    </ul>
                                </div>
                            </div>
                            <br />
                        }
                        <button class="form-inspect-share-button btn btn-large text-shadow-blue default-btn" type="submit" value="Submit" id="okbtn">Ok</button>
                        <button class="cancel-btn btn-link text-shadow-black" type="button" id="cancelbtn">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="DivBackgroundShareTacticDel" class="modal-backdrop fade in" style="z-index: 9999"></div>
</div>
<script src="~/Scripts/js/Select2/select2.js"></script>
<script type="text/javascript">
    $('#okbtn').click(function () {
        saveRoleActivity();
    });

    $('#cancelbtn').click(function () {
        $('#DivPartialShareTacticCheck').hide();
    });
</script>

RevenuePlanner/Views/Organization/OrganizationHierarchy.cshtml
@using RevenuePlanner.Helpers

<link href="@Url.Content("~/Content/css/jquery.treeview.css")" rel="stylesheet">
<script src="@Url.Content("~/Scripts/jquery.cookie.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.treeview.js")"></script>

@{
    ViewBag.Title = "Organization Hierarchy";
    ViewBag.ActiveMenu = RevenuePlanner.Helpers.Enums.ActiveMenu.Pref;
    Layout = "~/Views/Shared/_Layout.cshtml";
    var UserHierarchy = (List<RevenuePlanner.Models.UserHierarchyModel>)ViewBag.UserHierarchy;
    string varUrlnew = Url.Action("vieweditpermission", "Organization");
    string ViewPermissionURL = varUrlnew + "?Id=" + Sessions.User.UserId + "&Mode=MyPermission";
    ViewBag.PageTitle = "OrganizationHierarchy";////Added by Mitesh Vaishnav on 10-07-2014 for functional review point 49
    ViewBag.ModuleTitle = "Organization";////Added by Mitesh Vaishnav on 10-07-2014 for functional review point 49

}

@Html.Hidden("SuccMsg", TempData["SuccessMessage"])
@Html.Hidden("ErrMsg", TempData["ErrorMessage"])

@section Sidebar {
    @Html.Partial("~/Views/shared/_preferences.cshtml")
}

@* Added by Rahul Shah on 04/09/2015 for PL Ticket #1112*@
@if (TempData["SuccessMessage"] != null)
{
    if (!Convert.ToString(TempData["SuccessMessage"]).ToLower().Contains("model"))
    {
        <!--success message-->
        <div id="successMessage" class="alert hide alert-success message-position">
            <a class="close">×</a>
            <strong>Success.</strong> @Html.Raw(HttpUtility.HtmlDecode((string)TempData["SuccessMessage"]))
        </div>
        <!--success message-->
        TempData["SuccessMessage"] = "";
    }
}




<!--success message-->
<div id="successMessage" class="alert hide alert-success message-position">
    <a class="close">×</a>
    <strong>Success.</strong> @Html.Raw(HttpUtility.HtmlDecode((string)TempData["SuccessMessage"]))
</div>
<!--success message-->
<!--error message-->
<div id="errorMessage" class="alert hide alert-error message-position">
    <a class="close">×</a>
    <strong>Error!</strong> @Html.Raw(HttpUtility.HtmlDecode((string)TempData["ErrorMessage"]))
</div>
<!--error message-->
@*Commented by Rahul Shah on 03/09/2015 fo PL Ticket #1112*@
@*<ul class="nav nav-tabs">
        <li class="source-sans-proregular">
            <h2 class="title-header">Organization</h2>
        </li>
    </ul>*@
@*Added by Rahul Shah on 03/09/2015 fo PL Ticket #1112*@
<div id="hdrOrganization">
    <ul class="nav nav-tabs">
        <li class="source-sans-proregular">
            <h2 class="title-header">Organization</h2>
        </li>
    </ul>
</div>

<div id="hdrEditUser" style="display: none;">
    <ul class="nav nav-tabs margin-bottom0">
        <li class="source-sans-proregular">
            <h2 class="title-header">Edit User</h2>
        </li>
    </ul>
    <a class="link-gray" href="@Url.Action("OrganizationHierarchy", "Organization")">« BACK TO LIST</a>
</div>

<div class="row" id="dvEditUser" style="display: none;">
    <div class="span2 content-colum-left content-img-user">
        <div id="dvUserImage"></div>
    </div>
    <div id="dvEditUserDetails"></div>
</div>

<div class="padding-content cf source-sans-proregular" id="content">
    <div class="row">
        <div id="internalLink" class="span2 width216">
            @Html.Partial("~/Views/Organization/_organization.cshtml")
        </div>
        <div class="span9 hierarchy_wrapper">@*Modified by Bheru Shah on 14/09/2015 for PL #1596*@

            <ul id="treeView">
                <li>
                    <span>@Sessions.User.Client</span>
                    <ul>
                        @{
                            for (int i = 0; i < UserHierarchy.Count; i++)
                            {
                                var userId = UserHierarchy[i].UserId;
                                var userLabelId = "spnUserName" + userId;
                                var hdnEmailId = "hdnEmail" + userId;
                                var hdnPhoneId = "hdnPhone" + userId;
                                var hdnJobTitleId = "hdnJobTitle" + userId;
                                var stringClass = string.Empty;
                                if (UserHierarchy[i].subUsers.Count == 0)
                                {
                                    stringClass = "no-nesting";
                                }

                                string varUrl = Url.Action("vieweditpermission", "Organization");
                                string EditURL = varUrl + "?Id=" + UserHierarchy[i].UserId + "&Mode=Edit";
                                string ViewURL = varUrl + "?Id=" + UserHierarchy[i].UserId + "&Mode=View";

                                <li class="@stringClass">
                                    @if (UserHierarchy[i].subUsers.Count == 0)
                                    {
                                        <span class="hitarea"></span>
                                    }
                                    @*<span id="@userLabelId">@UserHierarchy[i].FirstName @UserHierarchy[i].LastName</span>*@ @*Commented by Rahul Shah on 03/09/2015 fo PL Ticket #1112*@
                                    <input id="@userLabelId" type="hidden" value="@UserHierarchy[i].FirstName @UserHierarchy[i].LastName" /> @*Added By Maitri Gandhi for #2147 observations on 2/5/2016*@
                                    <span id="@userId" class="treeview hover" style="text-decoration:underline">@UserHierarchy[i].FirstName @UserHierarchy[i].LastName</span> @*Added by Rahul Shah on 03/09/2015 fo PL Ticket #1112*@


                                    <span class="job-role" style="background-color:@UserHierarchy[i].ColorCode">@UserHierarchy[i].RoleTitle</span>
                                    @if ((bool)ViewBag.IsUserAdminAuthorized)
                                    {
                                        <a class="btn btn-default" href='@EditURL'>Edit</a>
                                    }
                                    <a class="btn btn-default" href='@ViewURL'>View</a>
                                    <a class="btn btn-default" onclick="showContactDetail('@userId');">Contact</a>
                                    <input type="hidden" id="@hdnEmailId" value="@UserHierarchy[i].Email" />
                                    <input type="hidden" id="@hdnPhoneId" value="@UserHierarchy[i].Phone" />
                                    <input type="hidden" id="@hdnJobTitleId" value="@UserHierarchy[i].JobTitle" />
                                    @{
                                if (UserHierarchy[i].subUsers.Count > 0)
                                {
                                    <ul>
                                        @for (int j = 0; j < UserHierarchy[i].subUsers.Count; j++)
                                        {
                                            Html.RenderPartial("_userHierarchy", UserHierarchy[i].subUsers[j]);
                                        }
                                    </ul>
                                }
                                    }

                                </li>
                            }
                        }
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>
<div hidden="true" style="margin-top: 80px;" class="modal-inspect-review-small hide" id="modal-container-186470">
    <div id="divPartial">
        <button data-dismiss="modal" class="close-x-icon"></button> @*Modified by Bhumika #2003 from "buttom" to "button"  *@
    </div>
    <div class="source-sans-proregular">
        <h2 id="lblUserName" class="title-simple source-sans-prolight"></h2>
        <p id="lblJobDetail"></p>
        <p><strong>Email: </strong><a id="lblEmail"></a></p>
        <p id="lblPhone"></p>
    </div>
</div>
<div class="modal-backdrop hide fade in"></div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#content_wraper").removeClass("span10 all-height").addClass("span10 padding-top40");

        $("#treeView").treeview({
            /*animated: "fast",*/
            collapsed: false,
            //persist: "cookie",
            toggle: function () {
                window.console && console.log("%o was toggled", this);
            }
        });

        $('.treeview li > ul li li').wrapInner("<span />");
        $('.treeview li > ul li ul > li:first-child').addClass("first");

        $(".close-x-icon").click(function () {
            hideContactDetail();
        });

        if ($('#SuccMsg').val() == null || $('#SuccMsg').val() == '') {
            $("#successMessage").slideUp(400);
        }
        else {
            $("#successMessage").slideDown(1200);
        }
        if ($('#ErrMsg').val() == null || $('#ErrMsg').val() == '') {
            $("#errorMessage").slideUp(400);
        }
        else {
            $("#errorMessage").slideDown(400);
            $("html, body").animate({ scrollTop: 0 }, 1000);
        }


    });

    function showContactDetail(userId) {
        @*Added By Maitri Gandhi for #2147 observations on 2/5/2016*@
        $("#lblUserName").text($("#spnUserName" + userId).val());  @*Modified By Maitri Gandhi for #2147 on 29/4/2016*@
        $("#lblJobDetail").text($("#hdnJobTitle" + userId).val());
        $("#lblEmail").attr("href", "mailto:" + $("#hdnEmail" + userId).val());
        $("#lblEmail").html($("#hdnEmail" + userId).val());
        $("#lblPhone").html("<strong>Phone: </strong>" + $("#hdnPhone" + userId).val());


        $("#modal-container-186470").show();
        $(".modal-backdrop").show();
    }

    function hideContactDetail() {
        $("#modal-container-186470").hide();
        $(".modal-backdrop").hide();
    }
    //Added by Rahul Shah on 03/09/2015 fo PL Ticket #1112

    function OnTeamMemberClick(userid) {
        $('#SuccMsg').val('');
        $('#ErrMsg').val('');
        $("#successMessage").slideUp(1);
        $("#errorMessage").slideUp(1);
        $.ajax({
            url: '@Url.Content("~/user/EditUserDetails")', type: "GET",
            data: { usrid: userid, src: 'myteam' },
            async: false,
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                if (data != null && data != 'undefined') {
                    if (data.serviceUnavailable != 'undefined' && data.serviceUnavailable == '#') {
                        //// Function to redirect to login page on unavailability of web service.
                        //// Added By: Maninder Singh Wadhva on 11/24/2014.
                        //// Ticket: 942 Exception handeling in Gameplan.
                        window.location = '@Url.Content(Common.RedirectOnServiceUnavailibilityPage)';
                    } else {
                        $("#content").css('display', 'none');
                        $("#hdrOrganization").css('display', 'none');
                        $("#hdrEditUser").css('display', 'block');
                        $("#dvEditUser").css('display', 'block');
                        $("#dvEditUserDetails").html(data);
                        LoadUserImage(userid);
                    }
                }
            }
        });
    }
    //Added by Rahul Shah on 03/09/2015 fo PL Ticket #1112
    function LoadUserImage(userid) {
        $.ajax({
            url: '@Url.Content("~/user/LoadUserImage")', type: "GET",
            data: { id: userid, width: 60, height: 60, src: 'myteam' },
            async: false,
            cache: false,
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                if (data != null && data != 'undefined') {
                    if (data.serviceUnavailable != 'undefined' && data.serviceUnavailable == '#') {
                        //// Function to redirect to login page on unavailability of web service.
                        //// Added By: Maninder Singh Wadhva on 11/24/2014.
                        //// Ticket: 942 Exception handeling in Gameplan.
                        window.location = '@Url.Content(Common.RedirectOnServiceUnavailibilityPage)';
                    }
                    else {
                        var imag = "<img  alt=''"
                         + "src='" + "data:image/jpg;base64,"
                         + data.base64imgage + "' class='img-user' style='height:140px; width:140px;'/>";
                        $("#dvUserImage").html(imag);
                    }
                }
            }
        });
    }
    //Added by Rahul Shah on 03/09/2015 fo PL Ticket #1112
    $(".treeview").click(function () {

        OnTeamMemberClick($(this).attr('Id'));

    });
</script>

RevenuePlanner/Views/Organization/_organization.cshtml
@using RevenuePlanner.Helpers

<!DOCTYPE html>
@{
    string varUrlnew = Url.Action("vieweditpermission", "Organization");
    string ViewPermissionURL = varUrlnew + "?Id=" + Sessions.User.UserId + "&Mode=MyPermission";
}

<div class="padding-right70">
    <ul class="nav nav-pills nav-stacked width216">

        <li id="MPermission"><a href='@ViewPermissionURL'>My Permissions</a></li>

        <li id="OHierarchy"><a href="@Url.Action("OrganizationHierarchy", "Organization")">Organization Hierarchy</a></li>
        <li id="Muser"><a href="@Url.Action("Index", "User")">Manage Users</a></li>         @*Added by Rahul Shah on 03/09/2015 fo PL Ticket #1112*@
        @if ((bool)ViewBag.IsUserAdminAuthorized)   // Added by Sohel Pathan on 24/06/2014 for PL ticket #519 to implement user permission Logic
        {

            <li id="MRoles"><a href="@Url.Content("~/Organization/ManageRoles/")">Manage Roles</a></li>
        }


    </ul>
</div>
<script>
    $(document).ready(
        function () {
            $('.nav nav-pills nav-stacked width216 li').each(function () {
                $(this).removeClass('active');
            });
            if ('@ViewBag.PageTitle' == 'OrganizationHierarchy') {
                $('#OHierarchy a').attr('href', '#');
                if (!$('#OHierarchy').hasClass('active')) {
                    $('#OHierarchy').addClass('active');
                }
            }
            else if ('@ViewBag.PageTitle' == 'MyPermission') {
                $('#MPermission a').attr('href', '#');
                if (!$('#MPermission').hasClass('active')) {
                    $('#MPermission').addClass('active');
                }
            }
                @*Added by Rahul Shah on 03/09/2015 fo PL Ticket #1112*@
            else if ('@ViewBag.PageTitle' == 'TeamMember') {
                if (!$('#Muser').hasClass('active')) {
                    $('#Muser').addClass('active');

                }
            }
            else if ('@ViewBag.PageTitle' == 'ManageRole') {
                $('#MRoles a').attr('href', '#');
                if (!$('#MRoles').hasClass('active')) {
                    $('#MRoles').addClass('active');
                }
            }
        }
            );
</script>


RevenuePlanner/Views/Organization/_userHierarchy.cshtml
@model RevenuePlanner.Models.UserHierarchyModel
@using RevenuePlanner.Helpers

@{
    var userId = Model.UserId;
    var userLabelId = "spnUserName" + userId;
    var hdnEmailId = "hdnEmail" + userId;
    var hdnPhoneId = "hdnPhone" + userId;
    var hdnJobTitleId = "hdnJobTitle" + userId;
    var stringClass = string.Empty;
    if (Model.subUsers.Count == 0)
    {
        stringClass = "no-nesting";
    }

    string varUrl = Url.Action("vieweditpermission", "Organization");
    string EditURL = varUrl + "?Id=" + Model.UserId + "&Mode=Edit";
    string ViewURL = varUrl + "?Id=" + Model.UserId + "&Mode=View";
}
<li class="@stringClass">
    @if (Model.subUsers.Count == 0)
    {
        <span class="hitarea"></span>
    }
    @*<span id="@userLabelId">@Model.FirstName @Model.LastName</span>*@ @*commented by Rahul Shah on 03/09/2015 fo PL Ticket #1112*@
    <input id="@userLabelId" type="hidden" value="@Model.FirstName @Model.LastName" /> @*Added By Maitri Gandhi for #2147 on 29/4/2016*@
    <span id="@userId" class="treeview hover" style="text-decoration:underline">@Model.FirstName @Model.LastName</span> @*Added by Rahul Shah on 03/09/2015 fo PL Ticket #1112*@
    <span class="job-role" style="background-color:@Model.ColorCode">@Model.RoleTitle</span>
    @if ((bool)ViewBag.IsUserAdminAuthorized)
    {
        <a class="btn btn-default" href='@EditURL'>Edit</a>
    }
    <a class="btn btn-default" href='@ViewURL'>View</a>
    <a class="btn btn-default" onclick="showContactDetail('@userId');">Contact</a>
    <input type="hidden" id="@hdnEmailId" value="@Model.Email" />
    <input type="hidden" id="@hdnPhoneId" value="@Model.Phone" />
    <input type="hidden" id="@hdnJobTitleId" value="@Model.JobTitle" />
    @{
        if (Model.subUsers.Count > 0)
        {
            <ul>
                @for (int j = 0; j < Model.subUsers.Count; j++)
                {
                    Html.RenderPartial("_userHierarchy", Model.subUsers[j]);
                }
            </ul>
        }
    }
</li>